// ================================================================

"use client";

import { useState, useTransition } from "react";
import { createPublicClient, http } from "viem";
import { baseSepolia } from "wagmi/chains";
import {
  REGISTRY_ADDRESS,
    REGISTRY_ABI,
      STATUS_LABELS,
        STATUS_COLORS,
          DeviceStatus,
            hashImei,
            } from "./contract";

            // Standalone public client — no wallet needed for read-only calls
            const publicClient = createPublicClient({
              chain:     baseSepolia,
                transport: http("https://sepolia.base.org"),
                });

                interface RegistryResult {
                  secretHash: `0x${string}`;
                    updateAt:   bigint;
                      status:     number;
                        imeiHash:   `0x${string}`;
                        }

                        export default function StatusChecker() {
                          const [deviceId,  setDeviceId]  = useState("");
                            const [result,    setResult]    = useState<RegistryResult | null>(null);
                              const [error,     setError]     = useState<string | null>(null);
                                const [isPending, startTransition] = useTransition();

                                  const handleCheck = () => {
                                      const trimmed = deviceId.trim();
                                          if (!trimmed) { setError("Please enter a device IMEI."); return; }
                                              setError(null);
                                                  setResult(null);

                                                      startTransition(async () => {
                                                            try {
                                                                    const imeiHash = hashImei(trimmed);
                                                                            const [secretHash, updateAt, status] = await publicClient.readContract({
                                                                                      address:      REGISTRY_ADDRESS,
                                                                                                abi:          REGISTRY_ABI,
                                                                                                          functionName: "registry",
                                                                                                                    args:         [imeiHash],
                                                                                                                            });
                                                                                                                                    setResult({ secretHash, updateAt, status: Number(status), imeiHash });
                                                                                                                                          } catch (err: unknown) {
                                                                                                                                                  const msg = err instanceof Error ? err.message : "Unknown error";
                                                                                                                                                          setError(`Failed to query registry: ${msg}`);
                                                                                                                                                                }
                                                                                                                                                                    });
                                                                                                                                                                      };

                                                                                                                                                                        const statusNum   = result?.status ?? -1;
                                                                                                                                                                          const statusText  = statusNum >= 0 ? STATUS_LABELS[statusNum] : null;
                                                                                                                                                                            const statusColor = statusNum >= 0 ? STATUS_COLORS[statusNum] : "";
                                                                                                                                                                              const isFlagged   = statusNum === DeviceStatus.Flagged;

                                                                                                                                                                                const formatDate = (unix: bigint) =>
                                                                                                                                                                                    unix === 0n ? "—" : new Date(Number(unix) * 1000).toLocaleString();

                                                                                                                                                                                      return (
                                                                                                                                                                                          <div className="bg-[#1A1A1A] border border-white/[0.07] rounded-2xl p-6 w-full max-w-lg">
                                                                                                                                                                                                {/* Header */}
                                                                                                                                                                                                      <div className="flex items-center gap-3 mb-6">
                                                                                                                                                                                                              <div className="w-9 h-9 rounded-xl bg-[#00F0FF]/10 border border-[#00F0FF]/25 flex items-center justify-center">
                                                                                                                                                                                                                        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                                                                                                                                                                                                                                    <circle cx="7" cy="7" r="5" stroke="#00F0FF" strokeWidth="1.5"/>
                                                                                                                                                                                                                                                <path d="M11 11l3 3" stroke="#00F0FF" strokeWidth="1.5" strokeLinecap="round"/>
                                                                                                                                                                                                                                                          </svg>
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                    <h2 className="text-[#E5E5E5] font-semibold text-base leading-tight">Check Device Status</h2>
                                                                                                                                                                                                                                                                                              <p className="text-[#888] text-xs mt-0.5">Read-only · No wallet required</p>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                  {/* Input row */}
                                                                                                                                                                                                                                                                                                                        <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                <div className="relative flex-1">
                                                                                                                                                                                                                                                                                                                                          <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#555] text-sm font-mono select-none">#</span>
                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                                                            inputMode="numeric"
                                                                                                                                                                                                                                                                                                                                                                                        maxLength={20}
                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Enter 15-digit IMEI"
                                                                                                                                                                                                                                                                                                                                                                                                                value={deviceId}
                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setDeviceId(e.target.value.replace(/\D/g, "").slice(0, 20))}
                                                                                                                                                                                                                                                                                                                                                                                                                                        onKeyDown={(e) => e.key === "Enter" && handleCheck()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full bg-[#0F0F0F] border border-white/[0.08] rounded-xl pl-8 pr-4 py-3 text-[#E5E5E5] text-sm font-mono placeholder:text-[#444] outline-none focus:border-[#00F0FF]/50 focus:ring-1 focus:ring-[#00F0FF]/20 transition-all duration-150"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleCheck}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={isPending || !deviceId.trim()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="px-5 py-3 rounded-xl font-semibold text-sm text-black bg-[#00F0FF] hover:bg-[#00F0FF]/90 disabled:opacity-40 disabled:cursor-not-allowed transition-all duration-150 active:scale-95 whitespace-nowrap flex items-center gap-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {isPending ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <SpinnerDark /> Checking…
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : "Check"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Error */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-3 flex items-start gap-2 bg-[#EF4444]/10 border border-[#EF4444]/25 rounded-xl p-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-[#EF4444] text-sm">⚠</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-[#EF4444] text-xs leading-relaxed">{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Result */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {result && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-4 animate-fade-up">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Status banner */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={`flex items-center gap-3 rounded-xl p-4 mb-3 border ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      isFlagged
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? "bg-[#EF4444]/8 border-[#EF4444]/25"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : statusNum === DeviceStatus.NotRegistered
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? "bg-white/[0.03] border-white/[0.07]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : "bg-[#22C55E]/8 border-[#22C55E]/25"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {isFlagged ? "🚨" : statusNum === DeviceStatus.Unflagged ? "✅" : "❓"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className={`font-semibold text-sm ${statusColor}`}>{statusText}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {isFlagged && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-[#EF4444]/70 text-xs mt-0.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            This device is reported stolen. Do not purchase.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Detail rows */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-[#0F0F0F] rounded-xl border border-white/[0.06] divide-y divide-white/[0.05]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { label: "IMEI Hash",    value: truncateHex(result.imeiHash),   mono: true,  accent: true  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { label: "Secret Hash",  value: truncateHex(result.secretHash), mono: true,  accent: false },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { label: "Last Updated", value: formatDate(result.updateAt),    mono: false, accent: false },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { label: "Network",      value: "Base Sepolia",                 mono: false, accent: false },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ].map(({ label, value, mono, accent }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={label} className="flex justify-between items-center px-4 py-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-[#666] text-xs uppercase tracking-widest">{label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className={`text-xs ${mono ? "font-mono" : ""} ${accent ? "text-[#00F0FF]" : "text-[#E5E5E5]"}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {value}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function SpinnerDark() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <svg className="animate-spin" width="14" height="14" viewBox="0 0 14 14" fill="none">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <circle cx="7" cy="7" r="5.5" stroke="rgba(0,0,0,0.2)" strokeWidth="2"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <path d="M7 1.5A5.5 5.5 0 0 1 12.5 7" stroke="#000" strokeWidth="2" strokeLinecap="round"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function truncateHex(hex: string, chars = 10): string {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!hex || hex === "0x" + "0".repeat(64)) return "—";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return `${hex.slice(0, chars)}…${hex.slice(-6)}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        